# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$go\
$python\
$kubernetes\
$cmd_duration\
$line_break\
$shell\
$character\
"""

[cmd_duration]
disabled = false
format = "took [$duration]($style) "

[kubernetes]
format = "[☸ ($context )](blue)"
disabled = false
