# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_commit\
$go\
$python\
$kubernetes\
$line_break\
$shell\
$character\
"""

[kubernetes]
format = "[☸ ($context )](blue)"
disabled = false
